import React from 'react'
import { View, Text } from '@react-pdf/renderer'
import { BrandingConfig } from '@/types/report'
import { createPDFStyles, createStyleSheet } from '../BaseTemplate'

interface ReportFooterProps {
  branding: BrandingConfig
  pageNumber?: number
  totalPages?: number
  showContact?: boolean
}

export function ReportFooter({ branding, pageNumber, totalPages, showContact = true }: ReportFooterProps) {
  const pdfStyles = createPDFStyles(branding)
  const styles = createStyleSheet(pdfStyles)
  
  return (
    <View style={styles.footer}>
      {/* Left side - Agency Contact */}
      {showContact && (
        <View style={{ flex: 1 }}>
          <Text style={[styles.caption, { color: pdfStyles.colors.primary, fontWeight: 'bold' }]}>
            {branding.name}
          </Text>
          <Text style={styles.caption}>
            {branding.email} • {branding.phone} • {branding.website}
          </Text>
        </View>
      )}
      
      {/* Center - Generated by */}
      <View style={{ flex: 1, textAlign: 'center' }}>
        <Text style={styles.caption}>
          Generated by Reportr • {new Date().toLocaleDateString()}
        </Text>
      </View>
      
      {/* Right side - Page Number */}
      {pageNumber && (
        <View style={{ flex: 1, textAlign: 'right' }}>
          <Text style={styles.caption}>
            Page {pageNumber}{totalPages && ` of ${totalPages}`}
          </Text>
        </View>
      )}
    </View>
  )
}