import React from 'react';
import { View, Text, StyleSheet } from '@react-pdf/renderer';

interface ReportFooterProps {
  branding: {
    whiteLabelEnabled?: boolean;
    enabled?: boolean;
    companyName: string;
    website?: string;
    email?: string;
    supportEmail?: string;
    primaryColor?: string;
  };
  pageNumber?: number;
  totalPages?: number;
}

function getFooterText(branding: ReportFooterProps['branding']): string {
  // If white-label is NOT enabled, show Reportr branding
  if (!branding.whiteLabelEnabled && !branding.enabled) {
    return "Generated by Reportr";
  }
  
  // If white-label IS enabled, show agency company name
  if (branding.companyName) {
    return branding.companyName;
  }
  
  // Fallback if no company name
  return "Generated by Reportr";
}

export const ReportFooter: React.FC<ReportFooterProps> = ({ branding, pageNumber, totalPages }) => {
  const styles = StyleSheet.create({
    footer: {
      position: 'absolute',
      bottom: 20,
      left: 40,
      right: 40,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: 15,
      borderTopWidth: 1,
      borderTopColor: '#E5E7EB',
    },
    footerLeft: {
      fontSize: 10,
      color: '#6B7280',
    },
    footerCenter: {
      fontSize: 10,
      color: '#6B7280',
    },
    footerRight: {
      fontSize: 10,
      color: '#6B7280',
    },
  });

  return (
    <View style={styles.footer} fixed>
      <Text style={styles.footerLeft}>{getFooterText(branding)}</Text>
      <Text style={styles.footerCenter}></Text>
      <Text style={styles.footerRight} render={({ pageNumber: currentPage, totalPages: total }) => 
        pageNumber && totalPages ? `Page ${pageNumber} of ${totalPages}` : `Page ${currentPage} of ${total}`
      } />
    </View>
  );
};