import React from 'react'
import { View, Text } from '@react-pdf/renderer'
import { BrandingConfig } from '@/types/report'
import { createPDFStyles, createStyleSheet } from '../BaseTemplate'

interface ReportFooterProps {
  branding: BrandingConfig
  pageNumber?: number
  totalPages?: number
  showContact?: boolean
}

function getFooterText(branding: BrandingConfig): string {
  // If white-label is NOT enabled, show Reportr branding
  if (!branding.whiteLabelEnabled) {
    return "Generated by Reportr | reportr.agency"
  }
  
  // White-label is enabled - show agency contact info
  const parts: string[] = []
  
  // Add website (remove protocol for cleaner display)
  if (branding.website) {
    const cleanWebsite = branding.website
      .replace('https://', '')
      .replace('http://', '')
      .replace(/\/$/, '') // Remove trailing slash
    parts.push(cleanWebsite)
  }
  
  // Add support email
  if (branding.supportEmail) {
    parts.push(branding.supportEmail)
  }
  
  // Join with pipe separator, or return empty if nothing to show
  return parts.length > 0 ? parts.join(' | ') : ''
}

export function ReportFooter({ branding, pageNumber, totalPages, showContact = true }: ReportFooterProps) {
  const pdfStyles = createPDFStyles(branding)
  const styles = createStyleSheet(pdfStyles)
  
  return (
    <View style={styles.footer}>
      {/* Left side - Agency Contact */}
      {showContact && (
        <View style={{ flex: 1 }}>
          <Text style={[styles.caption, { color: pdfStyles.colors.primary, fontWeight: 'bold' }]}>
            {branding.companyName}
          </Text>
          <Text style={styles.caption}>
            {branding.email} • {branding.phone} • {branding.website}
          </Text>
        </View>
      )}
      
      {/* Center - Generated by */}
      <View style={{ flex: 1, textAlign: 'center' }}>
        <Text style={styles.caption}>
          {getFooterText(branding)}{getFooterText(branding) ? ' • ' : ''}{new Date().toLocaleDateString()}
        </Text>
      </View>
      
      {/* Right side - Page Number */}
      {pageNumber && (
        <View style={{ flex: 1, textAlign: 'right' }}>
          <Text style={styles.caption}>
            Page {pageNumber}{totalPages && ` of ${totalPages}`}
          </Text>
        </View>
      )}
    </View>
  )
}