import { jsPDF } from 'jspdf'

interface ReportData {
  clientName: string
  startDate: string
  endDate: string
  agencyName?: string
  agencyLogo?: string
  gscData: {
    clicks: number
    impressions: number
    ctr: number
    position: number
    topQueries?: Array<{
      query: string
      clicks: number
      impressions: number
      ctr: number
      position: number
    }>
  }
  ga4Data: {
    users: number
    sessions: number
    bounceRate: number
    conversions: number
  }
}

export function generatePDFWithJsPDF(data: ReportData): ArrayBuffer {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.width
  const pageHeight = doc.internal.pageSize.height
  const margin = 20
  let yPosition = margin

  // Colors - Digital Frog Purple Branding (explicitly typed as tuples for jsPDF)
  const primaryPurple: [number, number, number] = [146, 51, 234] // #9233ea
  const lightPurple: [number, number, number] = [233, 213, 255] // #e9d5ff
  const veryLightPurple: [number, number, number] = [250, 245, 255] // #faf5ff
  const teal: [number, number, number] = [34, 211, 238] // #22d3ee
  const lightTeal: [number, number, number] = [165, 243, 252] // #a5f3fc
  const darkGray: [number, number, number] = [30, 41, 59] // #1e293b
  const mediumGray: [number, number, number] = [100, 116, 139] // #64748b
  const lightGray: [number, number, number] = [241, 245, 249] // #f1f5f9

  const formatNumber = (num: number): string => {
    return num.toLocaleString()
  }

  const formatDate = (dateStr: string): string => {
    return new Date(dateStr).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })
  }

  const agencyName = data.agencyName || 'Digital Frog Agency'
  const agencyWebsite = 'https://digitalfrog.co'
  const agencyEmail = 'jump@digitalfrog.co'
  const agencyPhone = '+56 9 9073 0352'

  // Helper: Add footer
  const addFooter = (pageNum?: number) => {
    doc.setDrawColor(...mediumGray)
    doc.setLineWidth(0.5)
    doc.line(margin, pageHeight - 25, pageWidth - margin, pageHeight - 25)

    doc.setFontSize(9)
    doc.setTextColor(...primaryPurple)
    doc.setFont('helvetica', 'bold')
    doc.text(agencyName, margin, pageHeight - 15)

    doc.setTextColor(...mediumGray)
    doc.setFont('helvetica', 'normal')
    doc.text(`${agencyEmail} • ${agencyPhone} • ${agencyWebsite}`, margin, pageHeight - 10)

    const generatedText = `Generated by Reportr • ${new Date().toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' })}`
    doc.text(generatedText, pageWidth / 2, pageHeight - 10, { align: 'center' })

    if (pageNum) {
      doc.text(`Page ${pageNum} of 2`, pageWidth - margin, pageHeight - 10, { align: 'right' })
    }
  }

  // Helper: Add header with separator
  const addPageHeader = () => {
    doc.setFontSize(10)
    doc.setTextColor(...primaryPurple)
    doc.setFont('helvetica', 'bold')
    doc.text(agencyName, margin, 15)

    doc.setTextColor(...darkGray)
    doc.setFont('helvetica', 'normal')
    doc.text(agencyWebsite, pageWidth - margin, 15, { align: 'right' })

    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text(data.clientName, pageWidth - margin, 22, { align: 'right' })

    doc.setTextColor(...mediumGray)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    
    doc.setDrawColor(...primaryPurple)
    doc.setLineWidth(2)
    doc.line(margin, 28, pageWidth - margin, 28)
  }

  // ======================
  // PAGE 1: COVER PAGE
  // ======================
  
  // Purple gradient background (simulated with rectangles)
  doc.setFillColor(...primaryPurple)
  doc.rect(0, 0, pageWidth, pageHeight, 'F')

  // White content area
  const contentY = 80
  const contentHeight = 170
  doc.setFillColor(255, 255, 255)
  doc.roundedRect(margin, contentY, pageWidth - 2 * margin, contentHeight, 5, 5, 'F')

  // Agency name on purple background
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text(agencyName, pageWidth / 2, 50, { align: 'center' })

  // Report title on white card
  doc.setTextColor(...primaryPurple)
  doc.setFontSize(28)
  doc.setFont('helvetica', 'bold')
  doc.text('Executive Summary Report', pageWidth / 2, contentY + 40, { align: 'center' })

  // Client name
  doc.setTextColor(...darkGray)
  doc.setFontSize(22)
  doc.text(data.clientName, pageWidth / 2, contentY + 70, { align: 'center' })

  // Date range
  doc.setFontSize(14)
  doc.setFont('helvetica', 'normal')
  doc.text(`${formatDate(data.startDate)} - ${formatDate(data.endDate)}`, pageWidth / 2, contentY + 95, { align: 'center' })

  // Separator line
  doc.setDrawColor(...teal)
  doc.setLineWidth(2)
  doc.line(pageWidth / 2 - 40, contentY + 105, pageWidth / 2 + 40, contentY + 105)

  // Generated date
  doc.setFontSize(11)
  doc.setTextColor(...mediumGray)
  doc.text(`Generated on ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`, pageWidth / 2, contentY + 130, { align: 'center' })

  // ======================
  // PAGE 2: EXECUTIVE SUMMARY
  // ======================
  
  doc.addPage()
  addPageHeader()
  yPosition = 40

  // Page title
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...primaryPurple)
  doc.text('Executive Summary', margin, yPosition)
  yPosition += 5

  // Underline
  doc.setDrawColor(...teal)
  doc.setLineWidth(1.5)
  doc.line(margin, yPosition, margin + 50, yPosition)
  yPosition += 15

  // Subtitle
  doc.setFontSize(11)
  doc.setTextColor(...mediumGray)
  doc.setFont('helvetica', 'normal')
  doc.text(`Performance overview for ${formatDate(data.startDate)} to ${formatDate(data.endDate)}`, margin, yPosition)
  yPosition += 20

  // Metric Cards (2x2 grid)
  const cardWidth = (pageWidth - 3 * margin) / 2
  const cardHeight = 45
  const cardSpacing = 10

  const summaryMetrics: Array<{
    label: string
    value: string
    description: string
    color: [number, number, number]
  }> = [
    { 
      label: 'Total Users', 
      value: formatNumber(data.ga4Data.users),
      description: 'Unique website visitors',
      color: lightPurple
    },
    { 
      label: 'Total Sessions', 
      value: formatNumber(data.ga4Data.sessions),
      description: 'Website visits',
      color: lightPurple
    },
    { 
      label: 'Bounce Rate', 
      value: `${data.ga4Data.bounceRate.toFixed(2)}%`,
      description: 'Single-page sessions (%)',
      color: lightPurple
    },
    { 
      label: 'Conversions', 
      value: formatNumber(data.ga4Data.conversions),
      description: 'Goal completions',
      color: lightPurple
    }
  ]

  let cardX = margin
  let cardY = yPosition

  summaryMetrics.forEach((metric, index) => {
    // Card background
    doc.setFillColor(...metric.color)
    doc.roundedRect(cardX, cardY, cardWidth, cardHeight, 3, 3, 'F')

    // Card border
    doc.setDrawColor(...primaryPurple)
    doc.setLineWidth(1)
    doc.roundedRect(cardX, cardY, cardWidth, cardHeight, 3, 3, 'S')

    // Label
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...primaryPurple)
    doc.text(metric.label, cardX + 8, cardY + 12)

    // Value
    doc.setFontSize(24)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...darkGray)
    doc.text(metric.value, cardX + 8, cardY + 28)

    // Description
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...mediumGray)
    doc.text(metric.description, cardX + 8, cardY + 38)

    // Move to next position
    if (index % 2 === 0) {
      cardX += cardWidth + cardSpacing
    } else {
      cardX = margin
      cardY += cardHeight + cardSpacing
    }
  })

  yPosition = cardY + cardHeight + 25

  // Key Insights Section
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...primaryPurple)
  doc.text('Key Insights', margin, yPosition)
  yPosition += 5

  doc.setDrawColor(...teal)
  doc.setLineWidth(1.5)
  doc.line(margin, yPosition, margin + 35, yPosition)
  yPosition += 15

  // Insight boxes
  const insights: Array<{
    title: string
    text: string
    bgColor: [number, number, number]
    borderColor: [number, number, number]
  }> = [
    {
      title: 'Traffic Overview',
      text: `Your website received ${formatNumber(data.ga4Data.users)} unique visitors across ${formatNumber(data.ga4Data.sessions)} sessions during this period. Visitors are returning to your site, indicating good content quality.`,
      bgColor: veryLightPurple,
      borderColor: lightPurple
    },
    {
      title: 'User Engagement',
      text: `${data.ga4Data.bounceRate < 40 ? 'Excellent' : data.ga4Data.bounceRate < 60 ? 'Good' : 'Moderate'} user engagement with ${data.ga4Data.bounceRate.toFixed(1)}% bounce rate.`,
      bgColor: [240, 253, 250] as [number, number, number], // light teal
      borderColor: lightTeal
    },
    {
      title: 'Conversion Performance',
      text: `${data.ga4Data.conversions > 0 ? `Great! You achieved ${formatNumber(data.ga4Data.conversions)} conversions during this period. Continue optimizing high-performing pages.` : 'Set up conversion tracking to measure the effectiveness of your marketing efforts.'}`,
      bgColor: [240, 253, 250] as [number, number, number],
      borderColor: lightTeal
    }
  ]

  insights.forEach(insight => {
    const boxHeight = 35
    
    // Box background
    doc.setFillColor(...insight.bgColor)
    doc.roundedRect(margin, yPosition, pageWidth - 2 * margin, boxHeight, 3, 3, 'F')

    // Box border
    doc.setDrawColor(...insight.borderColor)
    doc.setLineWidth(1)
    doc.roundedRect(margin, yPosition, pageWidth - 2 * margin, boxHeight, 3, 3, 'S')

    // Title
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...primaryPurple)
    doc.text(insight.title, margin + 5, yPosition + 10)

    // Text
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...darkGray)
    const textLines = doc.splitTextToSize(insight.text, pageWidth - 2 * margin - 10)
    doc.text(textLines, margin + 5, yPosition + 20)

    yPosition += boxHeight + 8
  })

  addFooter(1)

  // ======================
  // PAGE 3: RECOMMENDATIONS
  // ======================
  
  doc.addPage()
  addPageHeader()
  yPosition = 40

  // Page title
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...primaryPurple)
  doc.text('Strategic Recommendations', margin, yPosition)
  yPosition += 5

  doc.setDrawColor(...teal)
  doc.setLineWidth(1.5)
  doc.line(margin, yPosition, margin + 70, yPosition)
  yPosition += 15

  // Subtitle
  doc.setFontSize(11)
  doc.setTextColor(...mediumGray)
  doc.setFont('helvetica', 'normal')
  doc.text('Next steps to improve your digital performance', margin, yPosition)
  yPosition += 20

  // Priority Actions header
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...darkGray)
  doc.text('Priority Actions', margin, yPosition)
  yPosition += 15

  // Recommendations
  const recommendations = [
    {
      number: '1',
      title: 'Enhance Conversion Tracking',
      description: 'Set up detailed conversion tracking to measure the effectiveness of your marketing efforts.'
    },
    {
      number: '2',
      title: 'Optimize Conversion Funnel',
      description: 'Focus on improving the user journey and conversion funnel to maximize results from existing traffic.'
    },
    {
      number: '3',
      title: 'Regular Monitoring',
      description: 'Establish monthly reporting to track progress and identify trends early. Monitor key metrics consistently.'
    }
  ]

  recommendations.forEach(rec => {
    // Number badge
    doc.setFillColor(...primaryPurple)
    doc.circle(margin + 5, yPosition - 2, 4, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text(rec.number, margin + 5, yPosition, { align: 'center' })

    // Title
    doc.setTextColor(...primaryPurple)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text(rec.title, margin + 15, yPosition)

    // Description
    doc.setFontSize(10)
    doc.setTextColor(...darkGray)
    doc.setFont('helvetica', 'normal')
    const descLines = doc.splitTextToSize(rec.description, pageWidth - 2 * margin - 15)
    doc.text(descLines, margin + 15, yPosition + 8)

    yPosition += 25
  })

  yPosition += 10

  // Next Steps box
  doc.setFillColor(240, 253, 244) // light green
  doc.roundedRect(margin, yPosition, pageWidth - 2 * margin, 60, 3, 3, 'F')

  doc.setDrawColor(134, 239, 172) // green
  doc.setLineWidth(1)
  doc.roundedRect(margin, yPosition, pageWidth - 2 * margin, 60, 3, 3, 'S')

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...primaryPurple)
  doc.text('Next Steps', margin + 5, yPosition + 12)

  const nextSteps = [
    '• Schedule monthly performance reviews',
    '• Implement recommended optimizations',
    '• Set up automated monitoring alerts',
    '• Plan quarterly strategy adjustments'
  ]

  doc.setFontSize(10)
  doc.setTextColor(...darkGray)
  doc.setFont('helvetica', 'normal')
  nextSteps.forEach((step, index) => {
    doc.text(step, margin + 8, yPosition + 25 + (index * 8))
  })

  yPosition += 75

  // Contact section
  doc.setFontSize(11)
  doc.setTextColor(...mediumGray)
  doc.text('Questions about this report? Contact Digital Frog Agency', pageWidth / 2, yPosition, { align: 'center' })

  doc.setFontSize(11)
  doc.setTextColor(...primaryPurple)
  doc.setFont('helvetica', 'bold')
  doc.text(`${agencyEmail} • ${agencyPhone}`, pageWidth / 2, yPosition + 8, { align: 'center' })

  addFooter(2)

  return doc.output('arraybuffer')
}
